name: "GAP"
on:
  workflow_dispatch:
  pull_request:
  push:
  schedule:
    # Every day at 3:15 AM UTC
    - cron: '15 3 * * *'

jobs:
  test:
    name: "${{ matrix.gap-branch }} / ${{ matrix.os }} / ${{ matrix.ABI }}-bit"
    runs-on: "${{ matrix.os }}-latest"
    # Don't run this twice for PRs from branches in the same repository
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
        gap-branch:
          - master
          - stable-4.11
        ABI:
          - 64
          - 32

        include:
          # GAP stable-4.10
          - gap-branch: stable-4.10
            pkgs-to-clone: "datastructures images digraphs/digraphs"
            os: ubuntu
            ABI: 64
          # macOS job
          - gap-branch: master
            # to ensure datastructures>= v0.2.6
            # + digraphs >=1.5.0
            pkgs-to-clone: "datastructures digraphs/digraphs" 
            os: macos
            ABI: 64

    steps:
      - uses: actions/checkout@v2
      - name: "Install dependencies"
        if: ${{ runner.os == 'macOS' }}
        run: brew install automake
      - name: "Install GAP and clone/compile necessary packages"
        uses: gap-actions/setup-gap@v2
        env:
          # We don't understand why this is necessary. Hopefully it can be
          # removed in the fullness of time.
          LDFLAGS: "-pthread"
        with:
          GAP_PKGS_TO_CLONE: "${{ matrix.pkgs-to-clone }}"
          GAP_PKGS_TO_BUILD: "digraphs io orb datastructures profiling"
          GAPBRANCH: ${{ matrix.gap-branch }}
          ABI: ${{ matrix.ABI }}
      - name: "Build Semigroups"
        uses: gap-actions/build-pkg@v1
        with:
          ABI: ${{ matrix.ABI }}
      - name: "Run tst/teststandard.g"
        uses: gap-actions/run-pkg-tests@v2
        with:
          # This is the test file that is specified in our PackageInfo.g file.
          # This Action is *supposed* to use that file by default, but this is
          # not yet implemented, and instead the default is tst/testall.g.
          # Therefore we temporarily have to specify tst/teststandard.g here.
          GAP_TESTFILE: "tst/teststandard.g"
      - uses: gap-actions/process-coverage@v2
      - uses: codecov/codecov-action@v1
